### ISSUE TITLE
plugin doesn't work

### ISSUE THREAD

**Issue by lraieph0** [hkgnp/logseq-psummarise-plugin#1]
The problem is that when I close logseq and open it again, the plugin icon disappears and doesn't work, only when I close and open it again in the plugin screen does the plugin icon reappear, is there any way to fix this?
![image](https://user-images.githubusercontent.com/69003552/163781192-9c4b8ad5-9c70-4187-a483-5c01ab0b1deb.png)

version : 0.6.6
platform：windows11

Thanks for this great plugin, which is very helpful for working with raw material.

BTW,do you know about supermemo? ,which ideas is also further reading, and the special thing is that, as it finishes extracting the text, it also adds the clozs and highlighted sections to the cards , in preparation for the recitation work. It would be convenient if this plugin could do the same.

Of course, the current plugin is excellent, thanks again for the great work!

**Comment by lraieph0** [comment]
it seems that the problem is caused by logseq,  I've also had problems with other plugins disappearing .

**Comment by benjypng** [comment]
Feel free to re-open the ticket again if needed!

**Comment by benjypng** [comment]
> BTW,do you know about supermemo? ,which ideas is also further reading, and the special thing is that, as it finishes extracting the text, it also adds the clozs and highlighted sections to the cards , in preparation for the recitation work. It would be convenient if this plugin could do the same.
> 
> Of course, the current plugin is excellent, thanks again for the great work!

Hmmm, I can look into that but as it's not really part of my workflow, I am afraid I may not be able to commit to a timeline!

**Comment by lraieph0** [comment]
> > BTW,do you know about supermemo? ,which ideas is also further reading, and the special thing is that, as it finishes extracting the text, it also adds the clozs and highlighted sections to the cards , in preparation for the recitation work. It would be convenient if this plugin could do the same.
> > Of course, the current plugin is excellent, thanks again for the great work!
> 
> Hmmm, I can look into that but as it's not really part of my workflow, I am afraid I may not be able to commit to a timeline!

Thanks for the reply.

Ah, never mind, it's just a small request from me, and this plugin is quite adequate for my needs at the moment.
