### ISSUE TITLE
Better to be able to summarise a block rather than only a page

### ISSUE THREAD

**Issue by Simeonh2021** [hkgnp/logseq-psummarise-plugin#3]
Currently, this plugin can only help summarise content in a page (“[[，#”), which would be more flexible if it can summarise specific block (and all children blocks, all content under the parent block). 
Another plugin "extract" do this by right click the block button and click "extract". Maybe "progressive summarise" plugin can try this way (currently, the "summarise" button is on the top plugin bar).

**Comment by benjypng** [comment]
Progressively summarising block is available in 1.0.7.
Just right click the block.
