### ISSUE TITLE
Not extracting bold text from child blocks and also from long pages

### ISSUE THREAD

**Issue by AvijeetPrasad** [hkgnp/logseq-psummarise-plugin#5]
Hi, 

Thanks for this wonderful plugin. I am facing a couple of issues while trying to use it. 

- I am trying to summarize a lecture transcript, so it has considerably large number of blocks. And I guess due to the lazy loading of page in Logseq, only the highlights for top few blocks are being extracted.

- Also, I tried to right-click a parent block and extract highlights from child blocks, and it gave the error `No highlights found`. It works fine if I do it for a single block.

The following are the version details:
OS: macOS Monterey (12.3.1), Apple M1 Pro
Logseq version: 0.6.8
Plugin version: 1.0.7

**Comment by benjypng** [comment]
Do you mind sharing the lecture transcript so i can test, please?

As for the right clicking of a parent block, I don't think this plugin has such a function. It only progressively summarises the block itself and not its child blocks.

**Comment by AvijeetPrasad** [comment]
Hi, 

Thanks for your reply. Looks like the issue with long pages is resolved with the new version of Logseq (0.6.9) where the page loads much faster :)

Regarding the blocks, would it be possible in future then to have it extract the bold text from the child blocks also? This would greatly enhance the functionality in my view as then we can collect a number of blocks, put them under a parent block and extract highlights for these while not doing so for the rest of the page.

**Comment by benjypng** [comment]
Sure! Have created another issue for this FR: https://github.com/hkgnp/logseq-psummarise-plugin/issues/6
Will be closing this issue.
