### ISSUE TITLE
This plugin cannot extract all bold text.

### ISSUE THREAD

**Issue by skyline-123** [hkgnp/logseq-psummarise-plugin#7]
This plugin cannot extract all bold text.

**Comment by skyline-123** [comment]
Demo:

- # 渐进式总结：设计可发现笔记的实用技术
	- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*vTBT177SuhcgBEdPJwT9lA.jpeg?w=900&ssl=1)
	- 现代数字工具可以轻松地从各种来源“捕获”信息。我们知道如何拍摄图片、键入一些笔记、录制视频或扫描文档。将这些内容从外部世界带入数字世界是微不足道的。
	- 从一个应用程序到另一个应用程序获取已经数字化的内容甚至更容易。我们知道如何复制和粘贴文本、从网页中保存图像、存档电子邮件附件或导入视频文件。
	- 困难之处在于，不是将内容从一个地方传输到另一个地方，而是_随着时间的推移传输_。
	- 你知道我的意思：你读了一本书，投入数小时的脑力劳动来理解它提出的想法。你带着胜利的感觉结束了这本书，你已经获得了宝贵的知识。
	- 但是呢？
	- 你可能会尝试应用这本书推荐的基于科学的方法，却发现它并不像你想象的那么清晰。你可以尝试改变你的饮食、锻炼、沟通或工作方式，相信习惯的力量。但随后，生活的日常需求又回来了，你首先忘记了是什么激励了你。
	- 在这一点上，人们走不同的道路。有些人放弃了，给所有“自助”书籍贴上浪费时间的标签。其他人认为这只是记住他们读到的一切的问题，并投资于花哨的记忆技术。许多人成为“信息者”，强迫自己喂养无尽的书籍、文章和课程，希望有些东西能坚持下去。
	- 我想提出上述所有方法的替代方案：你读到的东西很好，有用，非常重要，_你只是在错误的时间阅读它_。
	- 您现在正在阅读时间管理技巧，但两年后，当您成为经理并对您的时间有更大的要求时，它们才会有用。
	- 您现在正在观看YouTube在线营销视频，但只有当您的新在线课程启动时，这些知识只能在9个月内使用。
	- 你现在正在与一个潜在客户谈论他的目标和挑战，但当你真正可以使用这些信息时，他将在明年竞标一份巨大的新合同。
	- 知识的挑战不是获得它。在我们的数字世界中，您几乎可以随时获得任何知识。
	- 挑战在于知道哪些知识值得获得。然后建立一个系统，_随着时间的推移_，在最适用和最需要的地方_推进_它的未来情况或问题或挑战。
	- 在那个将来，当你将这些知识直接应用于现实世界的挑战时，你不必担心记住它，整合它，甚至完全理解它。你只需要应用它，你理解中的任何差距都会很快暴露出来。当你用它解决一个真正的问题时，书籍知识已经变成了经验知识。经验知识是你永远随身携带的东西。
	- 这是“第二个大脑”的工作——一个外部的集成数字存储库，用于存储您学到的东西及其来源的资源。它是一个存储和检索系统，将知识片段打包到离散的数据包中，可以及时转发到各个点进行审查、使用或删除。
	- ## 使用渐进式总结
		- 在由4部分组成的[P.A.R.A.系列中](https://fortelabs.co/the-p-a-r-a-method-a-universal-system-for-organizing-digital-information-75a9da8bfb37)，我描述了一个用于组织来自任何来源的任何数字信息的通用系统。这是一个“足够好”的系统，根据笔记的_可操作性_（只需片刻即可确定），而不是其_含义_（模棱两可，取决于上下文）。
		- P.A.R.A.的四个顶级类别——项目、领域、资源和档案——旨在促进随着时间的推移转发知识的过程。
			- 通过在项目文件夹中放置注释，您基本上是在单个项目的**短时间内**将其安排以供审查
			- 每当您评估工作或生活的领域时，区域文件夹中的笔记都会被安排**不那么频繁**地**审查**
			- **如果您决定**对该主题**采取行动，**资源文件夹中的备注随时待审查
			- 存档文件夹中的笔记在**“冷存储”**中**，**如果需要，可以，但不会在任何特定时间进行审核
		- 请注意，我们已经重新创建了挠痒文件，除了严格的时间范围（每日、每周、每月、每年），它们是_偶然_安排_的_——如果发生X，当Y到达时，如果我想做Z等。
		- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*UL70dDF-RPYOhtoGX_rkJQ.jpeg?w=900&ssl=1)
		- 从应急方面进行规划为我们提供了规划和研究的所有好处，而不会将我们锁定在僵化的日常工作中。我们有能力大规模加速，使用我们积累的笔记库作为火箭燃料。但是，是否加速的实际决定，以及批判性地，我们_朝着哪个方向前进_，留给我们的未来自我，他年纪更大，更聪明。
		- P.A.R.A.回答了这些“知识包”是如何**组织的**：在离散的笔记中，根据可操作性分为4个类别，并使用RandomNote重新浮出水面。
		- 但现在我们转向一个更根本的问题：这些数据包是如何制作的？一旦我们捕获了一些东西，我们如何构建音符，使其在未来易于发现和使用？我们如何确保我们今天节省的东西为未来的项目增加价值，即使我们无法预测甚至无法想象这些项目可能是什么？
		- 这是渐进式总结的工作。
		- ### 笔记第一知识管理
			- 关于如何组织笔记计划（或实际上任何信息，但我将使用特定于笔记应用程序的术语）有两种小学思想：
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*chLWf5_BiDfcj03zu_KHCw.jpeg?w=900&ssl=1)
			- **标记优先的方法是**，笔记、笔记本和堆栈不应该有明确的层次结构。笔记被设想为一个不断变化的虚拟矩阵，由相互关联、自由浮动的想法组成。由于许多标签可以应用于一个音符，因此有多种途径可以发现任何给定的音符。在特定的笔记本和文件夹中查找笔记被视为限制性和静态。
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*A9MFYA0pXOWhCAYOAKcvqw.jpeg?w=900&ssl=1)
			- 虽然标签有其用途，但我认为它们不是一种主要的组织系统。根据我的经验，依赖标签太脆弱，需要太多的维护，过于统一地将注意力分散到所有笔记中，无论它们是否真正有价值。虚拟矩阵听起来很酷，很有未来感，但我们的大脑无法很好地处理这些抽象概念——我们理解直观和自动地将一件事放在一个地方。
			- 组织笔记的第二种传统方法是**笔记本优先**。这基本上将我们如何将物理世界中的东西（在一系列离散容器中）组织成数字世界。
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*e8Axv4OKw5fra2uSx6xxQA.jpeg?w=900&ssl=1)
			- 在我看来，笔记本优先比标记优先更好，主要是因为它远离了方向。它不会试图自动化和侵犯建立联系和查看模式的深刻直观的行为。P.A.R.A.本身就是一个笔记本优先系统。
			- 但是，如果我们止步于那里，对于一个基于创意产出的经济来说，它仍然远远不够。正如标记爱好者正确指出的那样，笔记本和文件夹实际上抑制了作为创造性生活方式核心的意外发现和随机性。
			- 我提出了一种打破僵局的方法：**注意优先的方法**。
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*fTOLyVYZPBoFlw-MEo4TPg.jpeg?w=900&ssl=1)
			- 我建议我们将**_单个笔记的设计_**作为主要因素，而不是标签或笔记本。这有很多优点：
				- 它适用于_任何其他_**组织系统**，不依赖它们（包括但不限于标签和笔记本，如果您想使用它们）
				- 它使您在笔记上所做的所有工作都**具有附加值**，因为您花费了近100%的时间直接参与内容本身
				- 它可以在**迁移**到其他设备、存储位置甚至程序**中**更容易，因为笔记内容比总体结构更有可能被保留
				- 它**培养**固有价值并高度可转移到其他活动的**技能**（简洁的沟通、找到想法的核心、视觉思维等）
				- 它使您的笔记更**清晰，对他人有用**（与仅供您使用的内部笔记本结构不同），促进协作和共享
			- 通过音符优先的方法，你的音符变得像单个**原子**——每个**原子**都有自己独特的特性，但可以组装成更强大的**元素、分子和化合物**。
		- ### 设计可发现的笔记
			- 注重注意的知识管理方法意味着我们必须考虑设计。从非常真实的意义上讲，您正在为苛刻的客户设计产品——Future You。
			- 未来 你不一定相信你放在笔记中的所有过去都是有价值的。Future You不耐烦，持怀疑态度，要求预先证明他们花在审查笔记上的时间是值得的。你必须“出售”审查给定笔记的想法，包括任何销售人员必须掌握[的所有阶段](https://www.thebalance.com/get-to-know-and-use-aida-39273)：获得**关注**，激发**兴趣**，建立**信誉**，激发**欲望**，并立即**采取行动**。
			- 好像这一切都不够吓人，你必须为每个音符这样做，而不要花_任何额外的时间_。你没有额外的时间，是吗？
			- 让我们从头开始：在每个设计的核心，我们正试图平衡优先级。你想要一样东西，但它必须与你_也_想要的东西平衡。
			- 您希望车辆保护其乘客，但您不能只是添加层层层的钛合金装甲镀层。你必须平衡安全与重量和成本。
			- 您希望手机的电池续航时间尽可能长，但你不能只给它10磅的电池砖。您必须平衡电池续航能力与尺寸和可用性。
			- 就笔记而言，我认为我们试图平衡的两个优先事项是**可发现**性和**理解性**。
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*8jDFbumKrLqHw_YtnDIGdw.jpeg?w=900&ssl=1)
			- 制作**可发现的**笔记需要使其小巧、简单且易于消化。我们使用**压缩**来实现这一点**：**创建高度浓缩的摘要，**没有所有的绒毛**。
			- 但我们也想让我们的笔记变得**容易理解**。这包括所有**上下文**：详细信息、示例和引用的来源，以确保没有任何东西从裂缝中掉下来。
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*QD4FVQe8CoMAxgjM3uwPFg.jpeg?w=900&ssl=1)
			- 这是一个困难的权衡_，_因为_你不能压缩某物而不失去一些上下文_。
			- 如果不放弃文章的大部分观点，你就无法总结文章。如果不剪掉大部分镜头，你就无法制作视频的高亮卷轴。你不能在不遗漏大部分想法的情况下进行18分钟的TED演讲。
			- 在决定保留什么时，你不可避免地决定扔掉什么。
		- ### 压缩 VS.上下文
			- 两者之间存在着自然的张力，压缩和上下文。
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*G9lCJtN0eBicuvctneSHVQ.jpeg?w=900&ssl=1)
			- 要传达任何事情，你必须压缩它，就像用一句明智的话传达大量的生活经验。但这样做时，你失去了许多从一开始就使这种智慧变得有价值的背景。
			- 让我们看看一些例子。
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*dq44FqjDaLiXwB9WvRXRyw.jpeg?w=900&ssl=1)
			- 如果我们压缩太多笔记，换句话说，我们会做一个过于简短的摘要，我们就会失去上下文，它就会失去所有意义。例如，在上面的注释中，它包含的信息是高度可发现的——我只需看一眼就能了解它的要点。
			- 但如果一年后我遇到这张纸条，我将不知道它意味着什么，也不知道为什么它很重要。它太压缩了。
			- 但我们也可以朝着相反的方向走得太远。如果我们让一些东西完全可以理解，换句话说，如果我们包括每个小细节和上下文，它就会失去其可发现性。
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*T6oXDnZWMNUCPN6uR9ywUA.jpeg?w=900&ssl=1)
			- 上面的例子是我关于任务管理软件Jira的笔记。它_有很多_上下文，因此非常容易理解。但它根本无法被发现。我可能需要几个小时和巨大的精神努力来通读这张纸条，并记住足够的上下文来决定它是否有用。要点和关键见解隐藏在噪音的某个地方。
			- 正确理解压缩和上下文之间的平衡并不是一件小事。当Future You决定是否查看此注释时，_秒数计算在内_。因为未来你可能会寻找问题的解决方案，而不是随便阅读，他们会在紧迫的时间表上做出快速决定。面对一堵价值可疑的文本墙，他们不太可能冒着花时间进行审查的风险。
			- 这意味着你过去的自我在这个笔记上所做的所有总结工作都被浪费了。当时没有回报，将来也没有回报。您成功地通过时间向前发送了一包信息，但不是处于它能够经受住的状态。
		- ### 机会主义压缩
			- 我发现大多数人在等式的上下文方面做得很好。我们知道如何在一本书、演示文稿或课堂上做详尽的笔记。
			- 因此，渐进总结侧重于重新平衡方程。它是一种_机会主义压缩_的方法——以小的瞬间总结和浓缩一条信息，在时间的过程中传播，并且只做信息应有的量或少。
			- 如果你还记得，压缩是提高可发现性的一种手段。因此，我们在创建笔记时的设计挑战是：
			-
			  > “我如何让我现在消费的东西很容易被发现，以便我未来的自己？”

			- 这不是一个简单的问题，因为你不知道你记得什么、对什么感兴趣或正在研究什么。你必须总结笔记，_而不知道它会用于什么_。这是通用总结，比为一个特定项目提取外卖更大的挑战。
			- 渐进式总结在总结的“层”中起作用。第0层是原始的完整源文本。
			- 第1层是我最初带入笔记程序的内容。我没有一套关于保留什么的明确标准。我只是捕捉任何有见地、有趣或有用的东西。
			- 这几乎可以包括任何类型的媒体，但对于这篇文章，我将专注于文本。_有很多_方法可以做到这一点：
				- 从我正在阅读的PDF中复制一段**文本**，并将其粘贴到Evernote[菜单栏助手](https://help.evernote.com/hc/en-us/articles/209005067-How-to-use-Evernote-Helper-for-quick-notes-and-screenshots)中
				- 在Evernote[移动应用程序](https://evernote.com/products)上将我的**随机想法**键入新笔记中
				- 将**Word文档**放在Mac基座上的Evernote图标上，并将其作为附件添加到笔记中
				- 使用[Bookcision](https://www.norbauer.com/bookcision/)从一本书中下载我所有的**Kindle亮点**，然后将它们复制并粘贴到新笔记中
				- 将包含有用信息**的电子邮件**转发到我的[个人导入地址](https://blog.evernote.com/blog/2012/04/20/quick-tip-friday-emailing-into-your-evernote-account/)，该地址会自动将整封电子邮件导入到备注中
				- 使用网络荧光[笔](http://getliner.com/)突出显示**在线文章**的最佳段落，该笔直接导出到Evernote
			- 上面的例子来自我推荐的程序[Evernote](https://evernote.com/)（iOS、Android、Mac、Windows、浏览器），但所有主要的笔记平台都以这样或那种方式支持上述功能：[Bear](http://www.bear-writer.com/)（Mac和iOS）、[Simplenote](https://simplenote.com/)（iOS、Android、Mac、Windows、Linux）、[Microsoft OneNote](https://www.onenote.com/)（iOS、Android、Mac、Windows）和[Google Keep](https://www.google.com/keep/)（浏览器、iOS、Android）。
			- 第1层是渐进总结的起点，就像构建其他一切的基石一样：
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*DFWCpLd-KPQssQZRf9GMlA.jpeg?w=900&ssl=1)
			- 第2层是第一轮真正的总结，其中我只粗化了我导入的段落的最佳部分。同样，我没有明确的标准。我寻找关键字、关键短语和关键句子，我认为它们代表了所讨论想法的核心或本质。
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*C14Mij5BoTie32_jGaOH5Q.jpeg?w=900&ssl=1)
			- 无论如何，当我已经在查看此注释时，我稍后会做这个加粗图层。我基本上将我已经花费的注意力用于双重目的：“购买”手头项目所需的信息，并总结笔记以备将来使用。如果你必须_注意_某事，能够双倍花钱是派上用场的。
			- 对于第3层，我切换到高亮显示，这样我就可以在所有粗体段落中分出较少的高亮显示段落。这一次，我正在寻找“最好的”，只有当它真正独特或有价值时，才会突出一些东西。同样，我只是在查看笔记时才添加第三层。
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*Dfkpa0eYIonHAubdDFqPWw.jpeg?w=900&ssl=1)
			- 对于第4层，我仍在总结，但除了突出别人的话，还记录我自己的话。对于少数最有见地的笔记，我在笔记顶部的非正式执行摘要中总结了第2层和第3层，用我自己的话重述了要点。
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*GdtcEbtCay2YCnKfoP4qmw.jpeg?w=900&ssl=1)
			- 请注意，之前的所有图层都保存在上下文中，让您可以自由地省略东西，而不必担心您会丢失它们。总结是有风险的——你可能对重要的事情做出了错误的决定。但有了多层保存笔记的安全网，您可以决定性地进行大胆的智力探险。
			- 最后，对于极少数来源，那些如此强大和令人兴奋的来源，我希望它们成为我_立即_思考和工作的一部分，我重新混合它们。在将它们拆开并从第1-4层的每个角度剖析它们后，我添加了自己的个性和创造力，并将它们转化为其他东西。
			- ![](https://i0.wp.com/cdn-images-1.medium.com/max/800/1*cs4WrYZDSERqIfHJBZoflQ.jpeg?w=900&ssl=1)
			- 这可能包括一篇博客文章解释、批评或扩展作者正在提出的论点，例如inStrategically [Constrained](https://fortelabs.co/strategically-constrained-how-to-turn-limitations-into-opportunities-4d20295c1a94)、[The Inner Game of Work](https://fortelabs.co/the-inner-game-of-work-focus-desire-and-working-free-d6312216c148)和[Supersizing the Mind](https://fortelabs.co/supersizing-the-mind-the-science-of-cognitive-extension-56d66c34a65f)。

**Comment by benjypng** [comment]
Sorry, I don't understand your demo. Could you share the steps that you have taken?

**Comment by skyline-123** [comment]
I mean, the demo above cannot extract all the bolded content. But I just upgraded Logseq, v0.7.1 no longer has this problem, thank you for your reply, this plugin just meets my needs, thank you very much.
