### ISSUE TITLE
Bold text is not fully extracted

### ISSUE THREAD

**Issue by skyline-123** [hkgnp/logseq-psummarise-plugin#8]
![image](https://user-images.githubusercontent.com/22638687/175753101-3853986a-a586-4618-8c92-5a7d7ec2fa66.png)
Bold text is not fully extracted.
Logseq version: v0.7.5
Plugin version: v1.1.0

**Comment by benjypng** [comment]
Could you copy the markdown text here so I can investigate further pls?

**Comment by skyline-123** [comment]
> Could you copy the markdown text here so I can investigate further pls?

- 心理学家加里•克莱因在他的经典决策书《权力的来源》中，正是提出了这一点，他指出了八种对专家来说看得见却对其他人来说看不见的知识：  
	- **新手没有注意到的模式。**  
	- **异常事件或没有发生的事或违反预期的事件。**  
	- **大局观。**  
	- **事情的运作方式。**  
	- **机会和即兴发挥。**  
	- **已经发生（过去）或将要发生（未来）的事件。**  
	- **新手无法察觉的细小差异。**  
	- **自身的局限。**

**Comment by benjypng** [comment]
Hmm, I cannot seem to replicate:

https://user-images.githubusercontent.com/47936793/175809124-b04daf82-9ca7-444b-839a-622c5c54b03f.mov

**Comment by skyline-123** [comment]
https://user-images.githubusercontent.com/22638687/175842550-e8bddc6e-05d5-4063-8afc-8d7086f63b62.mov

Well, it doesn't look good to locate the reason.

**Comment by skyline-123** [comment]
Is your Logseq version 0.7.5?

**Comment by benjypng** [comment]
Can you try using the icon instead (at the top, looks like a U with an underline)?

**Comment by skyline-123** [comment]
> Can you try using the icon instead (at the top, looks like a U with an underline)?

Tried it, same result

**Comment by benjypng** [comment]
Apologies, am still not able to replicate this issue.
