### ISSUE TITLE
The first time doesn't collect all highlights only the second time will collect all highlights. 

### ISSUE THREAD

**Issue by gandalf34** [hkgnp/logseq-psummarise-plugin#9]
Heres a video with the console open on the right

https://1drv.ms/v/s!AhitbfX5P7P2gZwgdlqyiDbBN4K5nQ?e=lrFCWA

**Comment by gandalf34** [comment]
No worries. Let me know if you need anything else.

**Comment by benjypng** [comment]
I am not able to re-produce this issue. As long as you follow the steps below, it should be fine.
1) Bold text.
2) Click the psummarise button in the toolbar (looks like <ins>U</ins>).
3) In the summarised text, highlight the text.
4) Then click "Extract Highlights".
